### PR TITLE
Restructuring of the directories and adding dependencies

### PR DESCRIPTION
**Pull request by anandgavai**
I restructured the mixin folder and created a subfolder within the directory scripts named "directive" where I have placed contents of this folder. Apart from this I have added dependencies to bower.json and Gruntfile.js

### CODE REVIEW

**Comment by mkuzak** [comment]
@anandgavai 

dfea82d2bb37581327f1405d2b6b44a32dd2598c
Please do not make copies of the the files, index.html changes are the result of wiredep or other grunt tasks. If you want to add or remove elements form index.html edit relevant files: package.json, bower.json by installing packages with --save option, for other things than package dependencies add them outside of areas edited by grunt tasks.

> > Actually the relative paths are changing the bower.json is uptodate

3edf6f6710a775b1a858cb25c44065605b4f728c
Adding links to packages in index.html should correspond to changes in package.json and bower.json.

> > The relative paths are causing me the problem. Do you have other suggestion for this ?

35c84070a27b7f27c3d217a71681dfcfd4a853e8
These are changes to diagnosis.html not change of the filename. Those changes should be explained in commit message. What is the role of new file replaceViewDialog.html?

> > Based on our last discussion I have changed the modal dialog to this replaceViewDialog this is the popup when we upload the file.

044fdf86b4e299e5c3bca43fbe7e4bd9c96c7930
Was the file customised? Looks like that’s a new file.
What does ng-table-to-csv.js do?

> > it is for exporting the csv template (download template)

7f00617177c2625329eb55ab095ef565e3ceeb39
If you’re adding dependencies explain what those do.

> > alright

57a841029db3f0e778ebc8ca377dec455cc5626e
If you’re removing a file, please explain why it’s not needed any more

992da1b48cd356eae5430cc7a6b9e641053df907
Do you mean folders.json file?

> > yes

9a202f2290928731aba39d9ecde0a9d85662cb55
There are no changes in this commit.

9f807e73be6039a3354ddd0111ff53ff3f770e65
There are no changes in this commit

c74b4ae697a91b41d864c897884e7cdf6cfb0793
I can see edited rule jshint. What do you mean by "this file has been automatically generated"?

4b6bb11029d9a467ccfa3d52f18484d700776438
6bce17f2e7b9f206c208660811769eb3549e24d3
Please use `git mv` to move files and commit the changes in one commit, otherwise it’s difficult to tell what is happening, there is one file deleted in one commit and other file created in the other.

> > I have used git mv and git rm to remove the files that were not needed ?

**Comment by mkuzak** [comment]
@anandgavai  next time please answer in separate comment, otherwise I don't see that you answered, and it also looks like my comments to my questions, there is not way of knowing you edited it

**Comment by mkuzak** [comment]
Relative paths mean, that you have sth installed without use of npm or bower,
if this is the case you have to edit index.html outside of regions edited by wiredep.

**Comment by anandgavai** [comment]
I have always used only npm and bower to install packages and components. However when I run grunt it always reverts back my index.html file. I do not know where can I configure this to make it not change my index.html file ? if you have any suggestion that would be very useful !

**Comment by mkuzak** [comment]
As i said above, only parts of index.html file are edited by wiredep. If you want to add something to this file you have to add it outside of those parts. Wiredep overwritten areas are annotated with comments. For example:

```
 <!-- bower:css -->
here goes wiredep pasted stuff
 <!-- endbower -->
```

**Comment by anandgavai** [comment]
Alright thanks, I will git it a try.

**Comment by mkuzak** [comment]
This pull request introduces an error when downloading template:

```
angular.js:13550 TypeError: tr.is is not a function
    at ng-table-to-csv.js:54
    at Object.forEach (angular.js:322)
    at Object.generate (ng-table-to-csv.js:50)
    at fn (eval at compile (angular.js:14432), <anonymous>:4:261)
    at expensiveCheckFn (angular.js:15485)
    at callback (angular.js:25018)
    at Scope.$eval (angular.js:17229)
    at Scope.$apply (angular.js:17329)
    at HTMLAnchorElement.<anonymous> (angular.js:25023)
    at defaultHandlerWrapper (angular.js:3456)
    at HTMLAnchorElement.eventHandler (angular.js:3444)
```

**Comment by mkuzak** [comment]
Adding a patient throws and error:

```
Error: $parse(...).assign is not a function
.link@http://localhost:9000/bower_components/ng-table-to-csv/dist/ng-table-to-csv.js:76:13
invokeLinkFn@http://localhost:9000/bower_components/angular/angular.js:9694:9
nodeLinkFn@http://localhost:9000/bower_components/angular/angular.js:9093:11
compositeLinkFn@http://localhost:9000/bower_components/angular/angular.js:8397:13
nodeLinkFn@http://localhost:9000/bower_components/angular/angular.js:9088:24
compositeLinkFn@http://localhost:9000/bower_components/angular/angular.js:8397:13
publicLinkFn@http://localhost:9000/bower_components/angular/angular.js:8277:30
lazyCompilation@http://localhost:9000/bower_components/angular/angular.js:8615:16
boundTranscludeFn@http://localhost:9000/bower_components/angular/angular.js:8414:16
controllersBoundTransclude@http://localhost:9000/bower_components/angular/angular.js:9143:20
ngRepeatAction@http://localhost:9000/bower_components/angular/angular.js:29003:15
$watchCollectionAction@http://localhost:9000/bower_components/angular/angular.js:16938:13
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9000/bower_components
...
```

**Pull request merged**
