### PR TITLE
csv import for email domains and email addresses

### PR DESCRIPTION
**Pull request by jvdzwaan**
refs #177

### CODE REVIEW

**Comment by mkuzak** [comment]
I get and error when running
```sh
pip install -r requirements.txt 
Could not detect requirement name, please specify one with #egg=
```
I think thats caused by line
```sh
-e git+https://github.com/kristjanr/django-csvimport.git@af1700ca650ec26763fa78bd44810c98e01866df
```

**Comment by jvdzwaan** [comment]
When I tested it locally it worked
I did have problems with dependencies for CairoSVG

Can you provide the output of pip? Or remove the line you think is causing it and then see if it works?

**Comment by mkuzak** [comment]
this is locally, the output is as mentioned above:
```sh
Could not detect requirement name, please specify one with #egg=
```
removing the line helps

**Comment by jvdzwaan** [comment]
Wait, you did post the error message...

Well it is a tricky situation, because with the Django-csvimport there is a pull request that solves a problem. Only it isn't merged yet, and the pull request was made some time ago. So I want to use that specific version.

As I said, it worked in my local installation. I don't really know about eggs. Are you using conda?

**Comment by mkuzak** [comment]
actually this is explained here
https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source
at the end of github url there needs to be #egg=package_name

**Comment by jvdzwaan** [comment]
Oh, that seems like a simple solution :)
Can you add it?

**Comment by mkuzak** [comment]
I think it works now, the message from pip is:
```
Could not find a tag or branch 'af1700ca650ec26763fa78bd44810c98e01866df', assuming commit.
```

**Comment by jvdzwaan** [comment]
Yes, I read about that message (didn't see it myself)

**Comment by mkuzak** [comment]
so the line in requirements.txt is now:
-e git+https://github.com/kristjanr/django-csvimport.git@af1700ca650ec26763fa78bd44810c98e01866df#egg=django-csvimport

**Comment by mkuzak** [comment]
Rest looks good. Can you correct this line? I'll merge it.

**Comment by jvdzwaan** [comment]
Sure, done!

**Comment by mkuzak** [comment]
awesome :)

**Pull request merged**
