### PR TITLE
Big refactor

### PR DESCRIPTION
**Pull request by jvdzwaan**
Please merge the other pull requests before this one.

It is a big refactor, that fixes many issues, most notably:
- taking into account intermediary and computed values for uploaded data #120 
- turning the data entry table into a proper table (although there are now some issues with the width of the table) #148 
- removed age and birthdate from the data entry table #161 
- data template is a tab separated file (although I think the exported data in the results tab still isn't, and I'm not sure excel saves the data as a tab separated file, the file extension is still csv, please comment) #172
- no delete button when there is only one patient #117
- a single 'data upload successful' message #118

Please test carefully, I may have introduced new errors.

### CODE REVIEW

**Comment by mkuzak** [comment]
awesome :) thanks

**Comment by JAvRZ** [comment]
Nice!

**Comment by mkuzak** [comment]
@jvdzwaan does this pull request contain code from the other two or they are separate and need to be merged too?

**Comment by jvdzwaan** [comment]
I think it contains commits from the #178 pull request. The other one is separate.

**Comment by mkuzak** [comment]
@jvdzwaan can you send me the example file you're using to upload?

**Comment by mkuzak** [comment]
I'm testing it on:
http://andi-test.andi-nlesc.surf-hosted.nl/
I upload the data, but when I press "Next" nothing happens, no errors in the console.

**Comment by mkuzak** [comment]
testing with your dataset, I get datatables error:
```
DataTables warning: table id=uni-var-table - Requested unknown parameter '5' for row 0, column 5. For more information about this error, please see http://datatables.net/tn/4
```

**Comment by jvdzwaan** [comment]
That is fixed in #179

**Comment by mkuzak** [comment]
ah, ok

**Comment by mkuzak** [comment]
merging

**Pull request merged**
