### PR TITLE
User management + login/logout using Django

### PR DESCRIPTION
**Pull request by jvdzwaan**
First version of user management and logging in and out functionality for the ANDI frontend.
- the functionality works (registering users, sending account activation email, logging in and out + user management through the admin interface)
- no checking of email domain yet
- appearance and layout have to be improved

Can you have a look? There are installation instructions in the readme. Run `python manage.py runserver` instead of `grunt serve`. No need to merge yet, but it would be nice if you could try it.

### CODE REVIEW

**Comment by mkuzak** [comment]
@jvdzwaan thank you,
I'm looking at the merge conflicts. It would help if you pulled and merged the changes from current `master`. I have removed the PanelCtrl.js but it comes  back in your code.

**Comment by jvdzwaan** [comment]
@mkuzak I think I did what you asked :)

**Comment by jvdzwaan** [comment]
Is it correct that the file `/utils/checkTestVarInfo.js` is currently not used?

**Comment by mkuzak** [comment]
It is a standalone script used to validate test variable information table.

**Comment by jvdzwaan** [comment]
Ah oke. Should you be able to run it in the webserver? It doesn;t really matter for now, it can always be moved to a different place later.

**Comment by mkuzak** [comment]
It should be run before running the webserver when they update test variable info, to make sure it's valid.

**Comment by mkuzak** [comment]
Thank you, no conflicts now 👍
I'll test it locally in your branch and merge when all is fine.

**Comment by mkuzak** [comment]
I've created a user account, but when I try to login I get the answer:
"It seems your account has been disabled.
If you feel that injustice has been done to you, feel free to contact the administrators to find out why"
Where can I get more information on user management?

**Comment by jvdzwaan** [comment]
Did you start the dummy mailserver? It should show a link with an activation code. If you paste the /acounts/...... part behind localhost:8000 your account should be activated.

You can probably also do it in the admin module, which can be found at localhost:8000/admin
To access the admin, you need to create a superuser: python manage.py createsuperuser
You might need to run python manage.py check_permissions afterwards

**Comment by mkuzak** [comment]
Thank you. I missed what was happening in the terminal window.

**Comment by mkuzak** [comment]
Actually you cannot activate from admin interface, but using the url with `/accounts/activate` works.

**Pull request merged**
